[#noparse]<html>
    <head>
        <title>${title}</title>
        <link href="${pageContext.request.contextPath}/default_theme/style.css" rel="stylesheet" type="text/css" media="screen">
    </head>
    <body>    
    
    	<div class="header">
		    <p>springmvc</p>
		</div>
		
		<div id="navcontainer">
			<ul id="navlist">
			    <li><a href="${pageContext.request.contextPath}/webapp/main/index">Main</a></li>
			    <li><a href="${pageContext.request.contextPath}/webapp/main/about">About</a></li>
			</ul>
		</div>
[/#noparse] 