CREATE TABLE DEMO.EMPLOYEES (
    EMPLOYEE_ID NUMBER(6) NOT NULL
    , FIRST_NAME VARCHAR2(20)
    , LAST_NAME VARCHAR2(25) NOT NULL
    , EMAIL VARCHAR2(25) NULL
    , PHONE_NUMBER VARCHAR2(20)
    , HIRE_DATE DATE NULL
    , SALARY NUMBER(8,2)
);

CREATE SEQUENCE DEMO.EMPLOYEES_SEQ
START WITH 1
INCREMENT BY 1 ;

/** We do not need trigger because Hibernate will take care of it! 
CREATE OR REPLACE TRIGGER DEMO.EMPLOYEES_SEQ_TRIGGER
BEFORE INSERT ON DEMO.EMPLOYEES
FOR EACH ROW
BEGIN
  SELECT DEMO.EMPLOYEES_SEQ.NEXTVAL 
  INTO :NEW.EMPLOYEE_ID FROM DUAL ;  
END ;
*/
